import { accessSync, constants, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";

import { defaultThreadId, ensureSessionLock, readPluginVersion, type SessionLockStatus } from "./session-lock.ts";

export type CliScope = "user" | "project";

export interface CliStatus {
  cli_on_path: boolean;
  path_command: string | null;
  plugin_root: string;
  plugin_version: string;
  current_cli: string;
  fallback_argv: string[];
  fallback_command: string;
  session_lock: SessionLockStatus;
  shim_target: string;
  shim_exists: boolean;
  shim_points_to_current_cli: boolean;
  path_contains_target_dir: boolean;
  recommended_action: "none" | "install-cli-shim-or-use-fallback";
}

export interface CliInstallResult {
  installed: boolean;
  target: string;
  scope: CliScope;
  plugin_root: string;
  current_cli: string;
  path_contains_target_dir: boolean;
}

export interface CliUninstallResult {
  removed: boolean;
  target: string;
  scope: CliScope;
}

function shellQuote(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function executable(path: string): boolean {
  try {
    accessSync(path, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

function findOnPath(command: string, envPath = process.env.PATH ?? ""): string | null {
  for (const directory of envPath.split(":").filter(Boolean)) {
    const candidate = join(directory, command);
    if (existsSync(candidate) && executable(candidate)) {
      return candidate;
    }
  }
  return null;
}

export function findPluginRoot(start: string): string {
  let current = isAbsolute(start) ? start : resolve(start);
  while (true) {
    if (existsSync(join(current, "package.json")) && existsSync(join(current, "bin", "coding-plugins.js"))) {
      return current;
    }
    const parent = dirname(current);
    if (parent === current) {
      throw new Error(`could not find coding-plugins root from ${start}`);
    }
    current = parent;
  }
}

export function defaultShimTarget(scope: CliScope, options: { root?: string } = {}): string {
  if (scope === "project") {
    return resolve(options.root ?? ".", ".coding-plugins", "bin", "coding-plugins");
  }
  return join(homedir(), ".local", "bin", "coding-plugins");
}

export function shimContent(options: { nodePath: string; cliPath: string }): string {
  return [
    "#!/usr/bin/env sh",
    "# coding-plugins-cli-shim",
    "# Generated by `coding-plugins cli install`.",
    `exec ${shellQuote(options.nodePath)} ${shellQuote(options.cliPath)} "$@"`,
    "",
  ].join("\n");
}

function sameShim(path: string, cliPath: string): boolean {
  if (!existsSync(path)) {
    return false;
  }
  const text = readFileSync(path, "utf8");
  return text.includes("# coding-plugins-cli-shim") && text.includes(cliPath);
}

function pathContains(directory: string, envPath = process.env.PATH ?? ""): boolean {
  const resolved = resolve(directory);
  return envPath
    .split(":")
    .filter(Boolean)
    .some((entry) => resolve(entry) === resolved);
}

export function cliStatus(options: { pluginRoot: string; target?: string; scope?: CliScope; root?: string; threadId?: string | null }): CliStatus {
  const scope = options.scope ?? "user";
  const root = resolve(options.root ?? ".");
  const target = resolve(options.target ?? defaultShimTarget(scope, { root }));
  const currentCli = join(options.pluginRoot, "bin", "coding-plugins.js");
  const pluginVersion = readPluginVersion(options.pluginRoot);
  const sessionLock = ensureSessionLock({
    root,
    pluginVersion,
    pluginRoot: options.pluginRoot,
    cliPath: currentCli,
    threadId: options.threadId ?? defaultThreadId(),
  });
  const fallbackCli = sessionLock.lock.cli_path || currentCli;
  const pathCommand = findOnPath("coding-plugins");
  const shimExists = existsSync(target);
  const shimPointsToCurrentCli = sameShim(target, currentCli);
  const targetDirectoryOnPath = pathContains(dirname(target));
  const cliOnPath = pathCommand !== null;
  return {
    cli_on_path: cliOnPath,
    path_command: pathCommand,
    plugin_root: options.pluginRoot,
    plugin_version: pluginVersion,
    current_cli: currentCli,
    fallback_argv: [process.execPath, fallbackCli],
    fallback_command: `${shellQuote(process.execPath)} ${shellQuote(fallbackCli)}`,
    session_lock: sessionLock,
    shim_target: target,
    shim_exists: shimExists,
    shim_points_to_current_cli: shimPointsToCurrentCli,
    path_contains_target_dir: targetDirectoryOnPath,
    recommended_action: cliOnPath || (shimPointsToCurrentCli && targetDirectoryOnPath) ? "none" : "install-cli-shim-or-use-fallback",
  };
}

export function installCliShim(options: {
  pluginRoot: string;
  target?: string;
  scope?: CliScope;
  root?: string;
  force?: boolean;
}): CliInstallResult {
  const scope = options.scope ?? "user";
  const target = resolve(options.target ?? defaultShimTarget(scope, { root: options.root }));
  const currentCli = join(options.pluginRoot, "bin", "coding-plugins.js");
  if (existsSync(target) && !sameShim(target, currentCli) && !options.force) {
    throw new Error(`refusing to overwrite existing non-coding-plugins shim: ${target}; pass --force to replace`);
  }
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, shimContent({ nodePath: process.execPath, cliPath: currentCli }), { encoding: "utf8", mode: 0o755 });
  return {
    installed: true,
    target,
    scope,
    plugin_root: options.pluginRoot,
    current_cli: currentCli,
    path_contains_target_dir: pathContains(dirname(target)),
  };
}

export function uninstallCliShim(options: { pluginRoot: string; target?: string; scope?: CliScope; root?: string }): CliUninstallResult {
  const scope = options.scope ?? "user";
  const target = resolve(options.target ?? defaultShimTarget(scope, { root: options.root }));
  const currentCli = join(options.pluginRoot, "bin", "coding-plugins.js");
  if (!existsSync(target)) {
    return { removed: false, target, scope };
  }
  if (!sameShim(target, currentCli)) {
    throw new Error(`refusing to remove non-coding-plugins shim: ${target}`);
  }
  rmSync(target);
  return { removed: true, target, scope };
}
